---
opensearch:
  biosample:
    index: biosample
    input_dir: output/biosample
    mappings: config/opensearch/default.json
    output_dir: biosample
  colocalisation:
    index: colocalisation
    input_dir: output/colocalisation
    mappings: config/opensearch/colocalisation.json
    output_dir: colocalisation
  credible_set:
    index: credible_set
    input_dir: output/credible_set
    mappings: config/opensearch/credible_set.json
    output_dir: credible_set
  croissant:
    index: downloads
    id_value: croissant
    input_dir: output/croissant
    mappings: config/opensearch/default.json
    output_dir: croissant
  disease:
    id_field: id
    index: disease
    input_dir: output/disease
    mappings: config/opensearch/default.json
    output_dir: disease
  disease_hpo:
    index: disease_hpo
    input_dir: output/disease_phenotype
    mappings: config/opensearch/default.json
    output_dir: disease_phenotype
  drug:
    index: drug
    input_dir: output/drug_molecule
    mappings: config/opensearch/default.json
    output_dir: drug_molecule
  drug_warnings:
    index: drug_warnings
    input_dir: output/drug_warning
    mappings: config/opensearch/default.json
    output_dir: drug_warning
  evidence_cancer_biomarkers:
    index: evidence_cancer_biomarkers
    input_dir: output/evidence_cancer_biomarkers
    mappings: config/opensearch/default.json
    output_dir: evidence/cancer_biomarkers
  evidence_cancer_gene_census:
    index: evidence_cancer_gene_census
    input_dir: output/evidence_cancer_gene_census
    mappings: config/opensearch/default.json
    output_dir: evidence/cancer_gene_census
  evidence_chembl:
    index: evidence_chembl
    input_dir: output/evidence_chembl
    mappings: config/opensearch/default.json
    output_dir: evidence/chembl
  evidence_clingen:
    index: evidence_clingen
    input_dir: output/evidence_clingen
    mappings: config/opensearch/default.json
    output_dir: evidence/clingen
  evidence_crispr:
    index: evidence_crispr
    input_dir: output/evidence_crispr
    mappings: config/opensearch/default.json
    output_dir: evidence/crispr
  evidence_crispr_screen:
    index: evidence_crispr_screen
    input_dir: output/evidence_crispr_screen
    mappings: config/opensearch/default.json
    output_dir: evidence/crispr_screen
  evidence_encore:
    index: evidence_encore
    input_dir: output/evidence_encore
    mappings: config/opensearch/default.json
    output_dir: evidence/encore
  evidence_europepmc:
    index: evidence_europepmc
    input_dir: output/evidence_europepmc
    mappings: config/opensearch/default.json
    output_dir: evidence/europepmc
  evidence_eva:
    index: evidence_eva
    input_dir: output/evidence_eva
    mappings: config/opensearch/default.json
    output_dir: evidence/eva
  evidence_eva_somatic:
    index: evidence_eva_somatic
    input_dir: output/evidence_eva_somatic
    mappings: config/opensearch/default.json
    output_dir: evidence/eva_somatic
  evidence_expression_atlas:
    index: evidence_expression_atlas
    input_dir: output/evidence_expression_atlas
    mappings: config/opensearch/default.json
    output_dir: evidence/expression_atlas
  evidence_gene2phenotype:
    index: evidence_gene2phenotype
    input_dir: output/evidence_gene2phenotype
    mappings: config/opensearch/default.json
    output_dir: evidence/gene2phenotype
  evidence_gene_burden:
    index: evidence_gene_burden
    input_dir: output/evidence_gene_burden
    mappings: config/opensearch/default.json
    output_dir: evidence/gene_burden
  evidence_genomics_england:
    index: evidence_genomics_england
    input_dir: output/evidence_genomics_england
    mappings: config/opensearch/default.json
    output_dir: evidence/genomics_england
  evidence_gwas_credible_sets:
    index: evidence_gwas_credible_sets
    input_dir: output/evidence_gwas_credible_sets
    mappings: config/opensearch/default.json
    output_dir: evidence/gwas_credible_sets
  evidence_impc:
    index: evidence_impc
    input_dir: output/evidence_impc
    mappings: config/opensearch/default.json
    output_dir: evidence/impc
  evidence_intogen:
    index: evidence_intogen
    input_dir: output/evidence_intogen
    mappings: config/opensearch/default.json
    output_dir: evidence/intogen
  evidence_orphanet:
    index: evidence_orphanet
    input_dir: output/evidence_orphanet
    mappings: config/opensearch/default.json
    output_dir: evidence/orphanet
  evidence_ot_crispr:
    index: evidence_ot_crispr
    input_dir: output/evidence_ot_crispr
    mappings: config/opensearch/default.json
    output_dir: evidence/ot_crispr
  evidence_ot_crispr_validation:
    index: evidence_ot_crispr_validation
    input_dir: output/evidence_ot_crispr_validation
    mappings: config/opensearch/default.json
    output_dir: evidence/ot_crispr_validation
  evidence_ot_genetics_portal:
    index: evidence_ot_genetics_portal
    input_dir: output/evidence_ot_genetics_portal
    mappings: config/opensearch/default.json
    output_dir: evidence/ot_genetics_portal
  evidence_progeny:
    index: evidence_progeny
    input_dir: output/evidence_progeny
    mappings: config/opensearch/default.json
    output_dir: evidence/progeny
  evidence_reactome:
    index: evidence_reactome
    input_dir: output/evidence_reactome
    mappings: config/opensearch/default.json
    output_dir: evidence/reactome
  evidence_slapenrich:
    index: evidence_slapenrich
    input_dir: output/evidence_slapenrich
    mappings: config/opensearch/default.json
    output_dir: evidence/slapenrich
  evidence_sysbio:
    index: evidence_sysbio
    input_dir: output/evidence_sysbio
    mappings: config/opensearch/default.json
    output_dir: evidence/sysbio
  evidence_uniprot_literature:
    index: evidence_uniprot_literature
    input_dir: output/evidence_uniprot_literature
    mappings: config/opensearch/default.json
    output_dir: evidence/uniprot_literature
  evidence_uniprot_variants:
    index: evidence_uniprot_variants
    input_dir: output/evidence_uniprot_variants
    mappings: config/opensearch/default.json
    output_dir: evidence/uniprot_variants
  expression:
    id_field: id
    index: expression
    input_dir: output/expression
    mappings: config/opensearch/default.json
    output_dir: expression
  facet_search_disease:
    index: facet_search_disease
    input_dir: view/search_facet_disease
    mappings: config/opensearch/facet_search.json
    output_dir: search_facet_disease
  facet_search_target:
    index: facet_search_target
    input_dir: view/search_facet_target
    mappings: config/opensearch/facet_search.json
    output_dir: search_facet_target
  go:
    id_field: id
    index: go
    input_dir: output/go
    mappings: config/opensearch/default.json
    output_dir: go
  gwas_index:
    index: gwas_index
    input_dir: output/study
    mappings: config/opensearch/study.json
    output_dir: study
  hpo:
    id_field: id
    index: hpo
    input_dir: output/disease_hpo
    mappings: config/opensearch/default.json
    output_dir: disease_hpo
  indication:
    index: indication
    input_dir: output/drug_indication
    mappings: config/opensearch/default.json
    output_dir: drug_indication
  interaction:
    index: interaction
    input_dir: output/interaction
    mappings: config/opensearch/default.json
    output_dir: interaction
  interaction_evidence:
    index: interaction_evidence
    input_dir: output/interaction_evidence
    mappings: config/opensearch/default.json
    output_dir: interaction_evidence
  known_drugs:
    index: known_drugs
    input_dir: output/known_drug
    mappings: config/opensearch/search_known_drugs.json
    output_dir: known_drug
  l2g_predictions:
    index: l2g_predictions
    input_dir: output/l2g_prediction
    mappings: config/opensearch/l2g_predictions.json
    output_dir: l2g_prediction
  mechanism_of_action:
    index: mechanism_of_action
    input_dir: output/drug_mechanism_of_action
    mappings: config/opensearch/default.json
    output_dir: drug_mechanism_of_action
  mouse_phenotypes:
    index: mouse_phenotypes
    input_dir: output/mouse_phenotype
    mappings: config/opensearch/default.json
    output_dir: mouse_phenotype
  openfda_faers:
    index: openfda_faers
    input_dir: output/openfda_significant_adverse_drug_reactions
    mappings: config/opensearch/default.json
    output_dir: openfda_significant_adverse_drug_reactions
  otar_projects:
    id_field: efo_id
    index: otar_projects
    input_dir: output/otar
    mappings: config/opensearch/default.json
    output_dir: otar
  pharmacogenomics:
    index: pharmacogenomics
    input_dir: output/pharmacogenomics
    mappings: config/opensearch/default.json
    output_dir: pharmacogenomics
  reactome:
    id_field: id
    index: reactome
    input_dir: output/reactome
    mappings: config/opensearch/default.json
    output_dir: reactome
  search_disease:
    index: search_disease
    input_dir: view/search_disease
    mappings: config/opensearch/search.json
    output_dir: search_disease
  search_drug:
    index: search_drug
    input_dir: view/search_drug
    mappings: config/opensearch/search.json
    output_dir: search_drug
  search_study:
    index: search_study
    input_dir: view/search_study
    mappings: config/opensearch/search.json
    output_dir: search_study
  search_target:
    index: search_target
    input_dir: view/search_target
    mappings: config/opensearch/search.json
    output_dir: search_target
  search_variant:
    index: search_variant
    input_dir: view/search_variant
    mappings: config/opensearch/search.json
    output_dir: search_variant
  so:
    id_field: id
    index: so
    input_dir: output/so
    mappings: config/opensearch/default.json
    output_dir: so
  # target:
  #   id_field: id
  #   index: target
  #   input_dir: output/target
  #   mappings: config/opensearch/default.json
  #   output_dir: target
  target_essentiality:
    id_field: id
    index: target_essentiality
    input_dir: output/target_essentiality
    mappings: config/opensearch/default.json
    output_dir: target_essentiality
  target_prioritisation:
    id_field: targetId
    index: target_prioritisation
    input_dir: output/target_prioritisation
    mappings: config/opensearch/default.json
    output_dir: target_prioritisation
  variant_index:
    index: variant_index
    input_dir: output/variant
    mappings: config/opensearch/default.json
    output_dir: variant
  protein_coding_coords:
    index: protein_coding_coords
    input_dir: view/coding_variant
    mappings: config/opensearch/default.json
    output_dir: protein_coding_coords
clickhouse:
  aotf:
    table: associations_otf_log
    input_dir: view/association_otf
    preload_script: config/clickhouse/schema/aotf.sql
    postload_script: config/clickhouse/scripts/aotf.sql
  baseline_expression:
    table: baseline_expression_log
    input_dir: output/baseline_expression
    preload_script: config/clickhouse/schema/baseline_expression.sql
    postload_script: config/clickhouse/scripts/baseline_expression.sql
  credible_sets:
    table: credible_sets_log
    input_dir: output/credible_set
    preload_script: config/clickhouse/schema/credible_sets.sql
    postload_script: config/clickhouse/scripts/credible_sets.sql
  interval:
    table: intervals_log
    input_dir: output/enhancer_to_gene
    preload_script: config/clickhouse/schema/intervals.sql
    postload_script: config/clickhouse/scripts/intervals.sql
  literature:
    table: literature_log
    input_dir: output/literature
    preload_script: config/clickhouse/schema/literature.sql
    postload_script: config/clickhouse/scripts/literature.sql
  w2v:
    table: ml_w2v_log
    input_dir: output/literature_vector
    preload_script: config/clickhouse/schema/w2v.sql
    postload_script: config/clickhouse/scripts/w2v.sql
  studies:
    table: studies_log
    input_dir: output/study
    preload_script: config/clickhouse/schema/studies.sql
    postload_script: config/clickhouse/scripts/studies.sql
  targets:
    table: targets_log
    input_dir: output/target
    preload_script: config/clickhouse/schema/targets.sql
    postload_script: config/clickhouse/scripts/targets.sql
  disease:
    table: disease_log
    input_dir: output/disease
    preload_script: config/clickhouse/schema/disease.sql
    postload_script: config/clickhouse/scripts/disease.sql
bigquery:
  association_by_datasource_direct:
    index: association_by_datasource_direct
    input_dir: output/association_by_datasource_direct
  association_by_datasource_indirect:
    index: association_by_datasource_indirect
    input_dir: output/association_by_datasource_indirect
  association_by_datatype_direct:
    index: association_by_datatype_direct
    input_dir: output/association_by_datatype_direct
  association_by_datatype_indirect:
    index: association_by_datatype_indirect
    input_dir: output/association_by_datatype_indirect
  association_by_overall_indirect:
    index: association_by_overall_indirect
    input_dir: output/association_by_overall_indirect
  association_overall_direct:
    index: association_overall_direct
    input_dir: output/association_overall_direct
  biosample:
    index: biosample
    input_dir: output/biosample
  colocalisation:
    index: colocalisation
    input_dir: output/colocalisation
  credible_set:
    index: credible_set
    input_dir: output/credible_set
  disease:
    index: disease
    input_dir: output/disease
  disease_hpo:
    index: disease_hpo
    input_dir: output/disease_hpo
  disease_phenotype:
    index: disease_phenotype
    input_dir: output/disease_phenotype
  drug_indication:
    index: drug_indication
    input_dir: output/drug_indication
  drug_mechanism_of_action:
    index: drug_mechanism_of_action
    input_dir: output/drug_mechanism_of_action
  drug_molecule:
    index: drug_molecule
    input_dir: output/drug_molecule
  drug_warning:
    index: drug_warning
    input_dir: output/drug_warning
  evidence_cancer_biomarkers:
    index: evidence_cancer_biomarkers
    input_dir: output/evidence_cancer_biomarkers
  evidence_cancer_gene_census:
    index: evidence_cancer_gene_census
    input_dir: output/evidence_cancer_gene_census
  evidence_chembl:
    index: evidence_chembl
    input_dir: output/evidence_chembl
  evidence_clingen:
    index: evidence_clingen
    input_dir: output/evidence_clingen
  evidence_crispr:
    index: evidence_crispr
    input_dir: output/evidence_crispr
  evidence_crispr_screen:
    index: evidence_crispr_screen
    input_dir: output/evidence_crispr_screen
  evidence_encore:
    index: evidence_encore
    input_dir: output/evidence_encore
  evidence_europepmc:
    index: evidence_europepmc
    input_dir: output/evidence_europepmc
  evidence_eva:
    index: evidence_eva
    input_dir: output/evidence_eva
  evidence_eva_somatic:
    index: evidence_eva_somatic
    input_dir: output/evidence_eva_somatic
  evidence_expression_atlas:
    index: evidence_expression_atlas
    input_dir: output/evidence_expression_atlas
  evidence_gene2phenotype:
    index: evidence_gene2phenotype
    input_dir: output/evidence_gene2phenotype
  evidence_gene_burden:
    index: evidence_gene_burden
    input_dir: output/evidence_gene_burden
  evidence_genomics_england:
    index: evidence_genomics_england
    input_dir: output/evidence_genomics_england
  evidence_gwas_credible_sets:
    index: evidence_gwas_credible_sets
    input_dir: output/evidence_gwas_credible_sets
  evidence_impc:
    index: evidence_impc
    input_dir: output/evidence_impc
  evidence_intogen:
    index: evidence_intogen
    input_dir: output/evidence_intogen
  evidence_orphanet:
    index: evidence_orphanet
    input_dir: output/evidence_orphanet
  evidence_reactome:
    index: evidence_reactome
    input_dir: output/evidence_reactome
  evidence_uniprot_literature:
    index: evidence_uniprot_literature
    input_dir: output/evidence_uniprot_literature
  evidence_uniprot_variants:
    index: evidence_uniprot_variants
    input_dir: output/evidence_uniprot_variants
  expression:
    index: expression
    input_dir: output/expression
  go:
    index: go
    input_dir: output/go
  interaction:
    index: interaction
    input_dir: output/interaction
  interaction_evidence:
    index: interaction_evidence
    input_dir: output/interaction_evidence
  interval:
    index: interval
    input_dir: output/enhancer_to_gene
  known_drug:
    index: known_drug
    input_dir: output/known_drug
  l2g_prediction:
    index: l2g_prediction
    input_dir: output/l2g_prediction
  literature:
    index: literature
    input_dir: output/literature
  literature_vector:
    index: literature_vector
    input_dir: output/literature_vector
  mouse_phenotype:
    index: mouse_phenotype
    input_dir: output/mouse_phenotype
  openfda_significant_adverse_drug_reactions:
    index: openfda_significant_adverse_drug_reactions
    input_dir: output/openfda_significant_adverse_drug_reactions
  openfda_significant_adverse_target_reactions:
    index: openfda_significant_adverse_target_reactions
    input_dir: output/openfda_significant_adverse_target_reactions
  pharmacogenomics:
    index: pharmacogenomics
    input_dir: output/pharmacogenomics
  reactome:
    index: reactome
    input_dir: output/reactome
  so:
    index: so
    input_dir: output/so
  study:
    index: study
    input_dir: output/study
  target:
    index: target
    input_dir: output/target
  target_essentiality:
    index: target_essentiality
    input_dir: output/target_essentiality
  target_prioritisation:
    index: target_prioritisation
    input_dir: output/target_prioritisation
  variant:
    index: variant
    input_dir: output/variant
  protein_coding_coords:
    index: protein_coding_coords
    input_dir: view/coding_variant
export:
  search_ebi_associations:
    input_dir: view/search_ebi_associations
    output_dir: search_ebi_associations
  epmc_cooccurrence:
    input_dir: intermediate/epmc_cooccurrence
    output_dir: epmc_cooccurrence
